package org.es4j.serialization;

//import org.es4j.eventstore.api.dotnet.CultureInfo;
import org.es4j.dotnet.CultureInfo;
import org.es4j.dotnet.ResourceManager;
//import org.es4j.eventstore.api.dotnet.ResourceManager;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
//[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
//[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Messages {

    private static ResourceManager resourceMan;
    private static CultureInfo resourceCulture;

    //[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    //internal
    Messages() {
    }

    // Returns the cached ResourceManager instance used by this class.
    //[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    private static ResourceManager resourceManager;
    public static ResourceManager getResourceManager() {
        if (resourceManager == null) { //object.ReferenceEquals(resourceMan, null)) {
            ResourceManager temp = new ResourceManager("EventStore.Serialization.Messages", Messages.class); // typeof(Messages).Assembly);
            resourceMan = temp;
        }
        return resourceMan;
    }

    // Overrides the current thread's CurrentUICulture property for all
    // resource lookups using this strongly typed resource class.
    //[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    private static CultureInfo culture;
    public static CultureInfo getCulture() {
        return resourceCulture;
    }
    public static void setCultureInfo(CultureInfo culture_) {
        resourceCulture = culture_;
    }

    // Looks up a localized string similar to Deserializing stream to object of type &apos;{0}&apos;..
    public static String DeserializingStream() {
        return ResourceManager.getString("DeserializingStream", resourceCulture);
    }

    // Looks up a localized string similar to Inspecting text-based stream contents..
    public static String InspectingTextStream() {
        return ResourceManager.getString("InspectingTextStream", resourceCulture);
    }

    // Looks up a localized string similar to The encryption key must be exactly 16 bytes..
    public static String InvalidKeyLength() {
        return ResourceManager.getString("InvalidKeyLength", resourceCulture);
    }

    // Looks up a localized string similar to Serializing object graph of type &apos;{0}&apos;..
    public static String SerializingGraph() {
        return ResourceManager.getString("SerializingGraph", resourceCulture);
    }
}
